<?php

namespace JobeetBundle\Repository;

/**
 * JobSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
